== Android Build
QTRobo lässt sich auch als *.apk* Applikation für Android Geräte bauen. Das Bauen der Applikation geschieht hierbei am Einfachsten in einer Windows (10) Umgebung, zum Beispiel in Form einer VM. 

Hierzu muss zum einen der QT Online Installer für Open Source Zwecke heruntergeladen und das QT Framework mit folgenden zusätzlichen Modulen installiert werden:

* Android
* Qt Charts
* Qt Script (deprecated)

image::images/TODO

Zum Qt Framework / Creator muss noch (zumindest ist dies die unkomplizierteste Variante) Android Studio installiert werden. Mit Android Studio installieren sich die benötigte Android SDK, Android Build Tools (Gradle etc.) und eine entsprechende Java Version. Diese Komponenten benötigt der QT Creator, um nachfolgend initial das Android Kit zu konfigurieren.

Nach der Installation von Android Studio kann nun im letzten Schritt Android als Zielplattform im QT Creator konfiguriert werden.

Die Konfiguration findet sich unter `Extras -> Geräte -> Android`.
Im Normalfall sollte QtCreator in diesem Tab die Konfiguration automatisch anbieten. Es müssen nur die entsprechenden Lizenzvereinbarungen etc. angenommen werden. 

image::images/TODO

Danach kann Qt Robo als Projekt im QT Creator geöffnet werden und es sollte ein entsprechendes Target Kit für Android angeboten werden. 